In [1]:
import numpy as np

In [2]:
# seed() --> for fix the random numbers, we will use seed().

In [3]:
np.random.seed(45)
a=np.random.randint(1,10,3)
a

array([4, 1, 6])

**view vs copy**

In [5]:
a=np.array([10,20,30,40,50,60,70,80,90])  ## view method means modification in the orignal array.
b=a[3:5]
b[:]=0
b
a

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [6]:
a=np.array([10,20,30,40,50,60,70,80,90]) ##copy method will not update your orignal array.
b=a[3:5].copy()
b[:]=0
b
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

**reshaping the array**

n(rows)*n(columns)=n(total_elements)


In [8]:
a=np.random.randint(1,50,12)
a

array([36,  5, 16,  2, 15,  9, 24, 47,  9, 13, 35, 25])

In [10]:
a.shape

(12,)

In [11]:
# 1*12 , 12*1
# 2*6 , 6*12
# 3*4 , 4*3

In [12]:
a.reshape(2,6)

array([[36,  5, 16,  2, 15,  9],
       [24, 47,  9, 13, 35, 25]])

In [13]:
a.reshape(3,4)

array([[36,  5, 16,  2],
       [15,  9, 24, 47],
       [ 9, 13, 35, 25]])

In [14]:
a.reshape(4,3)

array([[36,  5, 16],
       [ 2, 15,  9],
       [24, 47,  9],
       [13, 35, 25]])

In [15]:
a.reshape(2,15)   

ValueError: cannot reshape array of size 12 into shape (2,15)

**conditional selection in numpy**

In [16]:
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [19]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [20]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [21]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [23]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [24]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [25]:
a+b

array([[ 6,  8],
       [10, 12]])

In [26]:
a-b

array([[-4, -4],
       [-4, -4]])

In [27]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [28]:
a.dot(b)   # multiply of 2 matrix is done by using .dot() method.

array([[19, 22],
       [43, 50]])

In [29]:
# linSpace() --> it will return the values with same gap numbers.

In [30]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
# Unique() ---> it will return 3 array.
# (1). array-----> it will return array in which we have unique values.
# (2). return_index=True ---> unique value indexing.
# (3). return_counts=True ---> it will return frequeny of each unique values.

In [34]:
a=np.array([10,20,10,10,20,30,20,30,40,30,40,50])
np.unique(a, return_index=True, return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([ 0,  1,  5,  8, 11], dtype=int64),
 array([3, 3, 3, 2, 1], dtype=int64))

**Hstack and Vstack**

In [35]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])


In [36]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])