In [ ]:
#Numpy

In [ ]:
Numpy is a open source library of python and its use for scintific calculations.

In [ ]:
#why numpy?
#1. Homogenous data type
#2. less Memory
#3. fast execution 

In [1]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [4]:
a= [1,45,78,90]
type(a)

list

In [6]:
b= np.array(a)
b

array([ 1, 45, 78, 90])

In [7]:
b.ndim

1

In [8]:
p=[[1,2,3],[4,5,6],[7,8,9]]
q=np.array(p)
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print("Total shape:",q.shape) ## shape=row,column
print("Total Elements:",q.size) ## size=row*column
print("Total Dimension:",q.ndim) ## ndim--> dimension

Total shape: (3, 3)
Total Elements: 9
Total Dimension: 2


How can we create user define array?

In [11]:
a=[]
size=int(input("Enter the total elements"))
for i in range(size):
    val=int(input("Enter the number:"))
    a.append(val)
b=np.array(a)
b


Enter the total elements 5
Enter the number: 2
Enter the number: 3
Enter the number: 4
Enter the number: 5
Enter the number: 6


array([2, 3, 4, 5, 6])

Pre-defined functions in numpy

In [12]:
#Matrix--> rows,columns
# matrix--> n(r)=n(c)-->symmatrix matrix, n(r)1=n(c) --> asymmetric matrix
# diagonal positional elements=[(1,1),(2,2),(3,3),(4,4)....(n,n)]

In [13]:
#(1) .zeros() --> it will create an array that contain all 0.

In [15]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [17]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [21]:
b=np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
#3 .eye() -->it will create an array in which diagonal elements are 1 and rest all will be zero

In [23]:
a=np.eye(3,3)  ## symmetric
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
a=np.eye(4,5) # Asymmetric
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
#(4) .diag() --> it will create an array in which we can out custom diagonal values.

In [26]:
a=np.array([2,3,4,5,6,3])
b=np.diag(a)
b

array([[2, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 3]])

In [27]:
#(5) .Random-->
#(a) .Randint() -->it will generate random numbers in a given range.
#syntax: np.random.randint(min_number,max_number,total_numbers)


#(b)  .Rand() --> it will generate random numbers from 0 to 1.
#syntax:  np.random.rand(total_numbers)

In [28]:
a=np.random.randint(1,10,3)
a

array([1, 6, 3])

In [30]:
b=np.random.rand(5)
b

array([0.39029715, 0.75221487, 0.17273522, 0.71746918, 0.91813651])